### ISSUE TITLE
Refactoring and improvement

### ISSUE THREAD

**Issue by mrseneca** [dudarenko-dmitry/senla_training#10]
1) Entities should not contain other full entity in it, you can create relations just with IDs. 
![image](https://github.com/dudarenko-dmitry/senla_training/assets/31473268/9746d046-a64e-41d6-9594-cbd69a5140ad)
For example Guest is excessive, guestId is enough.
2) Work with Entities must be done on Service layer, but right now you passing to services already created entities. for example:
![image](https://github.com/dudarenko-dmitry/senla_training/assets/31473268/de963096-2272-4212-bc20-104329cdf593)
and you can count it as Controller Layer. In the service in same time: 
![image](https://github.com/dudarenko-dmitry/senla_training/assets/31473268/5e173ec5-a099-44eb-bf74-069459083bca)
Pass data to Service, and create entities in it
3) I don't really get idea with Storage classes:
![image](https://github.com/dudarenko-dmitry/senla_training/assets/31473268/8c7d7f3d-cd5c-4d90-8614-521056916e0c)
It just looks like an extra wrapper over collections. Collections in repositories would work almost the same, and in the future, when there would be a transition to DB, it would be easier to get rid of them than to change the structure with these additional classes. At this particular moment, it just seems like a complication, I don’t know, maybe I just don’t see the feature.
4) Also I did not like FreeRoom entity. We are creating two code entities for actually one logical entity. It seems to me that it would be possible to get by with one Room entity and an additional Order entity in order to calculate the availability and occupancy of rooms on a certain date at runtime, but perhaps again I don’t see the feature
5) Some instability in the code. Sometimes switches in original style, sometimes in lambda style. Sometimes there are for expressions, and according to the condition of the task, you need to switch to streams. Please check all small details

**Comment by dudarenko-dmitry** [comment]
Hi, Aleh.

I've already completed all these changes.
It took almost the same time as writing it all the first time :)

чт, 13 июл. 2023 г. в 16:56, Aleh Kryvets ***@***.***>:
